[package]
name = "hellow-world-ratatui"
version = "0.1.0"
description = "My first ratatui project!"
authors = ["Peter Hessey <peter.hessey@hotmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
